repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.11.17
    hooks:
      - id: uv-lock
  - repo: local
    hooks:
      - id: commitizen
        name: conventional commit
        entry: uv run cz check --commit-msg-file
        language: system
        stages: [commit-msg]
        pass_filenames: true
