name: Run linter and tests
description: Runs the format check, linter, type check and tests

inputs:
  python-version:
    description: Python version to use
    required: true
  envs:
    description: tox envs to run as comma-separated list
    required: true

runs:
  using: composite
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install tox
      shell: bash
      run: python3 -m pip install tox --user

    - name: Run checks
      shell: bash
      run: tox -e "${{ inputs.envs }}"