name: Check PR

on:
  pull_request:

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check
      uses: ./.github/actions/check

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [check]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with: # required to get the correct scm version
        fetch-depth: 0
        fetch-tags: true

    - name: Build
      uses: ./.github/actions/build
      with:
        use-scm-version: true
