name: Build and publish

on:
  push:
    branches: [main]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Check
      uses: ./.github/actions/check
      with:
        python-version: ${{ matrix.python-version }}
        envs: "${{ matrix.python-version == '3.12' && 'format-check, lint, spell-check, types, rich-only, ' }}${{ matrix.python-version }}"

  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [check]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      uses: ./.github/actions/build

  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: write
      pull-requests: write

    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}

    steps:
    - uses: googleapis/release-please-action@v4
      id: release-please
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        release-type: python

  publish:
    name: Publish
    needs: [release-please]
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest

    environment:
      name: pypi
      url: https://pypi.org/p/textual-kitty

    permissions:
      id-token: write

    steps:
    - name: Download distribution packages
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish
      uses: pypa/gh-action-pypi-publish@release/v1